### ISSUE TITLE
'module' object has no attribute 'DateTime' raised when calling delete on a funding source

### ISSUE THREAD

**Issue by dmwesterhoff** [Dwolla/dwolla-swagger-python#2]
An  exception is raised when trying to delete a funding source through the client.

note: though the call raises an exception it actually deletes the funding source properly in the back end

**Comment by spencerhunter** [comment]
@dmwesterhoff Can you update to the latest and give this another shot? This should fix the "AttributeError: 'module' object has no attribute 'DateTime'" you were seeing. https://github.com/Dwolla/dwolla-swagger-python/commit/844cd772c50703da9cd77f6ea320bfeac1be62c5

**Comment by mach-kernel** [comment]
This should really be fixed in `swagger-codegen` instead of manually patched in the generated library; it's probably a schema issue.

**Comment by dmwesterhoff** [comment]
OK, so unlink (delete linked account) now functions without an exception. However this patch will need to be applied as well to get transfer by id- which right now is producing the exact same DateTime module error

**Comment by dmwesterhoff** [comment]
Just tested, all is well
